# ==================================
# SERVER CONFIGURATION
# ==================================
server.port=9090
server.error.include-message=always
server.error.include-binding-errors=always

# ==================================
# DATASOURCE (SQL Server)
# ==================================
# Make sure your SQL Server Docker/Instance is running on port 14330
spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=FileSharing;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==================================
# JPA / HIBERNATE
# ==================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==================================
# JWT CONFIGURATION
# ==================================
jwt.secret=yGW7PgI5Zi7Iu9Q8Lvj4ylU8sq43RnXF5BMuP2++Hts=
jwt.expiration=86400000