# ==================================
# SERVER CONFIGURATION
# ==================================
server.address=0.0.0.0
server.port=9090
server.error.include-message=always
server.error.include-binding-errors=always
app.base-url=http://3.85.226.94:9090
# ==================================
# DATASOURCE (AWS RDS SQL Server)
# ==================================
spring.datasource.url=jdbc:sqlserver://file-sharing-db.cwz6we280s97.us-east-1.rds.amazonaws.com:1433;databaseName=FileSharing;encrypt=true;trustServerCertificate=true;
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==================================
# JPA / HIBERNATE
# ==================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==================================
# JWT CONFIGURATION
# ==================================
jwt.secret=yGW7PgI5Zi7Iu9Q8Lvj4ylU8sq43RnXF5BMuP2++Hts=
jwt.expiration=86400000