spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=FileSharing;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
server.error.include-binding-errors=always

jwt.secret=yGW7PgI5Zi7Iu9Q8Lvj4ylU8sq43RnXF5BMuP2++Hts=
jwt.expiration=86400000